Repository AutoInvestor/api-gateway, pull requests merged in 2025-04, with the labels that each got.

#1 Spring Application
  .github/workflows/post-commit-pipeline.yml
  .github/workflows/pull-request-pipeline.yml
  .gitignore
  HELP.md
  README.md
  build.gradle
  config/eclipse-java-formatter.xml
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
  settings.gradle
  src/main/java/io/autoinvestor/ApiGatewayApplication.java
  src/main/resources/application.properties
  src/test/java/io/autoinvestor/ApiGatewayApplicationTests.java
Labels: major

#2 Base `/` hello world to avoid Ingress failure
  src/main/java/io/autoinvestor/BaseController.java
Labels: patch

#3 AIR-47 Change base path to `/api`
  src/main/java/io/autoinvestor/BaseController.java
Labels: minor

#4 Feature/o auth2
  README.md
  build.gradle
  src/main/java/io/autoinvestor/configuration/SecurityConfiguration.java
  src/main/java/io/autoinvestor/filters/AddHeaderGatewayFilterFactory.java
  src/main/java/io/autoinvestor/filters/AuthorizeGatewayFilterFactory.java
  src/main/java/io/autoinvestor/filters/ExtractClaimGatewayFilterFactory.java
  src/main/java/io/autoinvestor/filters/Headers.java
  src/main/resources/application.properties
  src/main/resources/application.yml
Labels: major

#6 Dummy branch
  src/main/resources/application.yml
Labels: minor

#7 Config default
  src/main/java/io/autoinvestor/configuration/SecurityConfiguration.java
Labels: minor

#8 added gateway inline token hook endpoint
  src/main/java/io/autoinvestor/inlineHook/InLineResponseObject.java
  src/main/java/io/autoinvestor/inlineHook/InlineController.java
  src/main/java/io/autoinvestor/inlineHook/InlineService.java
Labels: minor

#9 Air 41 inline web hook
  src/main/java/io/autoinvestor/inlineHook/InlineController.java
Labels: minor

#11 Air 41 inline web hook
  src/main/resources/application.yml
Labels: minor

#12 Air 41 inline web hook
  src/main/resources/application.yml
Labels: minor

#13 Air 41 inline web hook
  src/main/resources/application.yml
Labels: minor

#14 Air 41 inline web hook
  src/main/resources/application.yml
Labels: minor

#15 Air 41 inline web hook
  src/main/resources/application.yml
Labels: minor
